version: '3.3'
services:

  redis:
    image: "redis:alpine"
      
  cloud-config:
    image: wmkang/cloud-config
    build: ./cloud-config
    ports:
      - 9001:9001

  cloud-eureka:
    image: wmkang/cloud-eureka
    build: ./cloud-eureka
    ports:
      - 9002:9002
    depends_on:
      - cloud-config

  cloud-gateway:
    image: wmkang/cloud-gateway
    build: ./cloud-gateway
    ports:
      - 8000:8000
    depends_on:
      - cloud-eureka

  svc-task:
    image: wmkang/svc-task
    build: ./svc-task
    ports:
      - 8001:8001
    depends_on:
      - cloud-config    
      - cloud-eureka
      - redis

  front-task:
    image: wmkang/front-task
    build: ./front-task
    ports:
      - 80:3000
    depends_on:
      - svc-task
    stdin_open: true
