
spring:
  datasource:
    hikari:
      username: sa
      password:
      manage:
        jdbc-url: jdbc:h2:file:./h2/manage
      service-1:
        jdbc-url: jdbc:h2:file:./h2/service1
      service-2:
        jdbc-url: jdbc:h2:file:./h2/service2
  redis:
    host: localhost
    port: 6379
#    password: passwd
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${app.port.cloud-eureka}/eureka/

app:
  log-base-path: ${user.home}/wmkang/logs
  file:
    upload:
      base-path: ${user.home}/wmkang/storage/upload
  audit:
    enable: true
  debug:
    api:
      expose-error-message: true
    log:
      beans:
        switch: OFF
        type: OBJECT
      classpath: OFF
      parameters:
        http: ON
        controller: ON
